---
title: "Climate Summaries by Station"
author: ''
date: ''
output: html_document
---

Click on markers on map or on links in table below to access station summary pages. These pages will have current plots as well as access to historical data from the period of record for each station.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,results='asis', echo=FALSE}
leaflet(width="100%") %>% addProviderTiles(providers$Esri.DeLorme, options = providerTileOptions(minZoom = 6)) %>%
  #addMarkers(lng=stationThin$lon, lat=stationThin$lat, popup=stationThin$names,
  #           labelOptions = labelOptions(noHide = T))
  addMarkers(stnlinksDF$lon, stnlinksDF$lat, popup = stnlinksDF$`Station Page Link`,
             label = stnlinksDF$Station)

```  
------

```{r,results='asis', echo=FALSE}
datatable(stnlinksDF[,c(5,4)], class = 'cell-border compact stripe', escape = FALSE, rownames = FALSE)
```

<p>&nbsp;</p>

------

<div align="center">
  <em>[Return to main page](https://cals.arizona.edu/climate/misc/stations/index.html)</em>
</div>

------

<div align="center">
  <em>[Climate Science Applications Program - University of Arizona Cooperative Extension](http://cals.arizona.edu/climate/)</em>
</div>

<div align="center">
  <h6>
  Last Updated: "`r format(Sys.time(), '%m-%d-%Y')`"© 2020 The Arizona Board of Regents. All contents copyrighted. All rights reserved.</h6>
</div>