---
title: "`r pageTitle`"
author: ''
date: ''
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,results='asis', echo=FALSE}
library(leaflet)
leaflet(width="100%") %>% addProviderTiles(providers$Esri.DeLorme, options = providerTileOptions(minZoom = 6)) %>%
  #addMarkers(lng=stationThin$lon, lat=stationThin$lat, popup=stationThin$names,
  #           labelOptions = labelOptions(noHide = T))
  addCircleMarkers(leafletTable$lon, leafletTable$lat,
                   radius = 8,
                   color = "black",
                   fillColor =  pal(leafletTable$`Total Precip (in)`),
                   fillOpacity = 0.8,
                   popup = lapply(stnLabs, htmltools::HTML),
                   label = lapply(stnLabs, htmltools::HTML)
                   ) %>%
   addLegend("bottomright", pal = pal, values = leafletTable$`Total Precip (in)`,
    title = "Total Precip (in)", opacity = 1)

```  

```{r results='asis', echo=FALSE}
cat(paste0(' <span style="color:red"> <font size="4"> Summary period: ', format(as.Date(Date1),"%m-%d-%Y"),' through ',format(as.Date(Date2),"%m-%d-%Y"), '</font></span>'))
```
-------

```{r,results='asis', echo=FALSE}
library(DT)
datatable(summary, class = 'cell-border compact stripe', escape = FALSE, rownames = FALSE)
```

<div align="center">
  <em>[Climate Science Applications Program - University of Arizona Cooperative Extension](http://cals.arizona.edu/climate/)</em>
</div>

------
<div align="center">
  <h6>
  Last Updated: "`r format(Sys.time(), '%m-%d-%Y')`"© 2020 The Arizona Board of Regents. All contents copyrighted. All rights reserved.</h6>
</div>
