---
title: "`r markdownTitle`"
author: ''
date: ''
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## {.tabset .tabset-fade}

<div align="center">
### Precipitation
```{r,results='asis', echo=FALSE}
library(plotly)
  p1<-ggplot(tempTable, aes(x=Year,y=`Total Precip (in)`, fill=`Missing Precip (days)`))+
        geom_bar(stat = 'identity',show.legend = FALSE)+
        scale_fill_gradient(low = "green4", high = "red")+
        geom_hline(yintercept = mean(tempTable$`Total Precip (in)`))
        
      ggplotly(p1)
```
(Color indicates number of missing days, horizontal line is long-term mean)


### Temperature 
```{r,results='asis', echo=FALSE}
  p2<-ggplot(tempTable, aes(x=Year,y=`Avg Temp (F)`))+
        geom_line()+
        geom_point(aes(color=`Missing Temp (days)`),show.legend = FALSE)+
        scale_color_gradient(low = "yellow", high = "red")+
        geom_hline(yintercept = mean(tempTable$`Avg Temp (F)`))
      ggplotly(p2)
```
(Color indicates number of missing days, horizontal line is long-term mean)

### Station Map
```{r,results='asis', echo=FALSE}
library(leaflet)
leaflet(width="100%") %>% addProviderTiles(providers$Esri.DeLorme) %>%
  setView(stationLatLon$lon, stationLatLon$lat, zoom = 8) %>%
  addMarkers(lng=stationLatLon$lon, lat=stationLatLon$lat, popup=stationName)
```
</div>

------
```{r,results='asis', echo=FALSE}
kable(tempMean, caption="Period of Record Averages")
```
------

## {.tabset .tabset-fade}

<div align="center">
### Summary Stats
```{r,results='asis', echo=FALSE}
library(DT)
datatable(tempTable, class = 'cell-border compact stripe', escape = FALSE, rownames = FALSE)
```

### Anomalies
```{r,results='asis', echo=FALSE}
datatable(tempAnom, class = 'cell-border compact stripe', escape = FALSE, rownames = FALSE)
```

</div>


------
add in links to other seasons and main page



